baseURL = "https://pabloduenas.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "BitÃ¡cora de Viaje de Pablo "
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = "@PabloDuenas"
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "@PabloDuenas22"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
